name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: false  # Bắt buộc là false
          persist-credentials: false # Bổ sung dòng này để tránh xung đột quyền

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3 # Nên dùng v3 thay vì v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build website
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
